name: Versionado automático

on:
  push:
    branches:
      - main
      - release
      - develop

jobs:
  tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Obtener el último tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "Último tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Calcular nueva versión
        id: calc_version
        run: |
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.get_tag.outputs.tag }}"
          BRANCH="${GITHUB_REF##*/}"

          if [ "$BRANCH" = "main" ]; then
            ((MAJOR+=1))
            MINOR=0
            PATCH=0
          elif [ "$BRANCH" = "release" ]; then
            ((MINOR+=1))
            PATCH=0
          else  # develop
            ((PATCH+=1))
          fi

          NEW_TAG="${MAJOR}.${MINOR}.${PATCH}"
          echo "Nueva versión: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Crear nuevo tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ steps.calc_version.outputs.new_tag }}
          git push origin ${{ steps.calc_version.outputs.new_tag }}